GET http://localhost:3000
Content-Type: application/json
api: 123


GET http://localhost:3000/api/v1/products?size=50



POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "Practical Steel Pants 2",
    "price": 664,
    "image": "https://picsum.photos/seed/cvdjqslTh/640/480"
}

GET http://localhost:3000/api/v1/products/49cad225-c926-4850-a6c9-d32014f0b70b


DELETE  http://localhost:3000/api/v1/products/efbdc6a9-bd3a-4c85-9fac-d309340cbb84


PATCH  http://localhost:3000/api/v1/products/efbdc6a9-bd3a-4c85-9fac-d309340cbb84
Content-Type: application/json

{
    "name": "Practical Steel Pants 3",
    "price":1000
}

//authentication
//por defecto debe llamarse username pero se puede cambiar
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"aaa@gmail.com",
    "password":"aaa123"
}

POST http://localhost:3000/user/
Content-Type: application/json

{
    "email":"aaa2@gmail.com",
    "password":"aaa1232"
    
}

POST http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3MDEwNjQ0NjV9.Yxwu_E7ovqb-s0-Bno7idgCCk8T4juXlyKoXSn5mp9I 

{
    "email":"aaa2@gmail.com",
    "password":"aaa1232"
    
}

DELETE  http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDEwNjc1Mzd9.BffyLj28PBYPzew-EYDOkcVCHtsdwEnNLprsK_2OMq8 

PATCH  http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDEwNjc1Mzd9.BffyLj28PBYPzew-EYDOkcVCHtsdwEnNLprsK_2OMq8

{
    "email":"aaa2@gmail.com",
    "password":"aaa1232"
    
}

// ejemplos con base de datos
GET http://localhost:3000/api/v1/products?size=50


GET http://localhost:3000/api/v1/products?size=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInJvbGUiOltdLCJpYXQiOjE3MDIyNzU0MzN9.e7kf4v_1nVzFE0OYWVYKh9dmFUq_CALaCLcG_wEaJWM

//crear usuario (encriptación de la password)

POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInJvbGUiOlt7ImlkIjoxLCJuYW1lIjoiYWRtaW5pc3RyYXRvciIsInBlcm1pc3Npb25TY2FsZSI6OTksIlVzZXJSb2xlIjp7ImlkIjoxLCJ1c2VySWQiOjQsInJvbGVJZCI6MX19LHsiaWQiOjIsIm5hbWUiOiJjdXN0b21lciIsInBlcm1pc3Npb25TY2FsZSI6MSwiVXNlclJvbGUiOnsiaWQiOjIsInVzZXJJZCI6NCwicm9sZUlkIjoyfX1dLCJpYXQiOjE3MDIyNzIxOTV9.D88wFyL_-jPILS9-1lXaePkrpSLTY3McLsRlbWIZGGI

{
    "username": "Herrera2",
    "email": "jhonny2@gmail.com",
    "password": "jhoony prueba"
}

POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInJvbGUiOlt7ImlkIjoxLCJuYW1lIjoiYWRtaW5pc3RyYXRvciIsInBlcm1pc3Npb25TY2FsZSI6OTksIlVzZXJSb2xlIjp7ImlkIjoxLCJ1c2VySWQiOjQsInJvbGVJZCI6MX19LHsiaWQiOjIsIm5hbWUiOiJjdXN0b21lciIsInBlcm1pc3Npb25TY2FsZSI6MSwiVXNlclJvbGUiOnsiaWQiOjIsInVzZXJJZCI6NCwicm9sZUlkIjoyfX1dLCJpYXQiOjE3MDIyNzIxOTV9.D88wFyL_-jPILS9-1lXaePkrpSLTY3McLsRlbWIZGGI

{
    "username": "usuario_Prueba",
    "email": "pruebacursoplatzi@gmail.com",
    "password": "prueba"
}


//validar password con bcrypt y generar jwt
POST http://localhost:3000/api/v1/user/authenticate
Content-Type: application/json

{
    "email": "jhonnyherrera1998@gmail.com",
    "password": "admin"
}
 
POST http://localhost:3000/api/v1/user/authenticate
Content-Type: application/json

{
    "email": "jhonny.javier.herrera.rincon@pwc.com",
    "password": "admin"
}

//usuario con rol administrator, no olvidar cambiar las ids de los user a eliminar 
DELETE  http://localhost:3000/api/v1/user/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInJvbGUiOlt7ImlkIjoxLCJuYW1lIjoiYWRtaW5pc3RyYXRvciIsInBlcm1pc3Npb25TY2FsZSI6OTksIlVzZXJSb2xlIjp7ImlkIjoxLCJ1c2VySWQiOjQsInJvbGVJZCI6MX19LHsiaWQiOjIsIm5hbWUiOiJjdXN0b21lciIsInBlcm1pc3Npb25TY2FsZSI6MSwiVXNlclJvbGUiOnsiaWQiOjIsInVzZXJJZCI6NCwicm9sZUlkIjoyfX1dLCJpYXQiOjE3MDIyNzIxOTV9.D88wFyL_-jPILS9-1lXaePkrpSLTY3McLsRlbWIZGGI

//usuario sin role adminitrator
DELETE  http://localhost:3000/api/v1/user/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInJvbGUiOltdLCJpYXQiOjE3MDIyNzM3MzR9.qsLOC1_F977YuJj5cWZJglqvu4iflOXK1Fg41kzxMeA



